### ISSUE TITLE
Idea of a "direct render"

### ISSUE THREAD

**Issue by kevinresol** [MVCoconut/coconut.react-core#18]
Normally we write a View like the following, which will create an actual instance of "Wrapper":

```haxe
class Wrapper extends View {
	@:attr var foo:Int;
	function render() '<Wrapped foo=${foo}/>';
}
```

Thanks to JS, in some scenario I couldn't afford the extra wrapper instance. Because some framework will look into the rendered child's type and perform magic. So what I did is to manually write `fromHxx` and produce a non-wrapped child.

```haxe
class Wrapper {
	public static function fromHxx(attr:{foo:Int}) {
		return React.createElement(Wrapped, {foo: foo});
	}
}
```

I think it is possible for coconut to support this, given some criteria is met (e.g. no state)

**Comment by back2dos** [comment]
What's ironic is that `<Wrapper>` in JSX will always do `React.createElement(Wrapper)` :D

I think nowadays, this would do quite fine:

```haxe
function Wrapper(attr:{foo:Int})
  return hxx('<Wrapped foo=$foo>');
```

It's probably the shortest route to having `<Wrapper foo=$foo />` be fully equivalent to `<Wrapped foo=$foo />` ;)

**Comment by kevinresol** [comment]
Yes, it is not a designed-for-react framework. So things are [a bit hacky](https://github.com/visgl/deck.gl/issues/3009#issuecomment-485510599) there. The point is that even JS users can't use a wrapper react component to render the thing. So code are highly non-reusable.

> It's probably the shortest route

Yeah, but I want to pretend it as much as possible as a "normal" View. So I can `import Wrapper` instead of `Import Wrapper.StaticFunction` to get the function renderer.

Anyway, so far my manual `fromHxx` approach seem to work without problems, and it is very edge case indeed. So may be not worth the trouble.

**Comment by back2dos** [comment]
> Yeah, but I want to pretend it as much as possible as a "normal" View. So I can `import Wrapper` instead of `Import Wrapper.StaticFunction` to get the function renderer.

You can put `function Wrapper` into `Wrapper.hx` and then `import Wrapper;` will behave as desired.
