### ISSUE TITLE
Unexpected rendering order?

### ISSUE THREAD

**Issue by kevinresol** [MVCoconut/coconut.react-core#26]
I am trying to use the data structure proposed in https://github.com/MVCoconut/coconut.data/issues/74

What I observed is a child view trying to update itself sooner than its wrapping parent. I understand that each view individually registers their own observations on the data they depend on, but I am not sure if there are some not-so-obvious ordering rules I missed?

```haxe
import tink.pure.*;
import tink.state.*;
import coconut.ui.*;
import coconut.data.*;
import js.Browser.*;

using tink.CoreApi;

class Main extends View {
	
	@:attr var value:Value<Vector<Obj>, Vector<Obj>> = new Value({
		raw: new State(([{foo: 'bar'}]:Vector<Obj>)),
		parse: Success,
	});
	
	function render() {
		trace('render Main ${value.raw.length}');
		return @hxx '
		<>
			<for ${i in 0...value.raw.length}>
				<Sub value=${value.sub(raw -> raw[i], (raw, nu) -> raw.with(i, nu), Success)} onClick=${value.raw = []}/>
			</for>
		</>
	';
	}
	
	
	
	static function main() {
		Renderer.mount(document.getElementById('app'), '<Main/>');
	}
}


typedef Obj = {
	final foo:String;
}

class Sub extends View {
	@:attr var value:Value<Obj, Obj>;
	@:attr var onClick:Void->Void;
	function render() {
		trace('render Sub ${value.raw}');
		return @hxx '<div onclick=${onClick}>${value.raw == null ? null : value.raw.foo}</div>';
	}
}


class Value<Raw, Result> implements Model {
	@:shared var raw:Raw;
	@:constant var parse:Raw->Outcome<Result, Error>;
	@:computed var parsed:Outcome<Result, Error> = parse(raw);
	public inline function sub<SubRaw, SubResult>(read:Raw->SubRaw, write:(Raw, SubRaw) -> Raw,
			parse:SubRaw->Outcome<SubResult, Error>):Value<SubRaw, SubResult> {
		return new Value({
			raw: observables.raw.transform({read: read, write: v -> write(raw, v)}),
			parse: parse,
		});
	}
}
```

After clicking the button, I expect it to print:

```
render Main 0
```

and I expect the `Sub` to be unmounted from the render tree, but actually it prints:

```
render Sub null
render Main 0
```

Therefore if the null check inside `Sub` is omitted, the app will crash with NPE.

**Comment by back2dos** [comment]
Seems to be working now (added test here and made coconut.ui suite pass again). The main issue was that children subscribed to changes before their parents, meaning if a change affected both, the child would rerender first. This is no longer the case.

All that said, render order in React will probably never be fully predictable, because React reserves the right to do only partial updates (although as far as I understand that's concurrent mode only, which is not what we use by default).

**Comment by kevinresol** [comment]
Thanks very much 🙏
