### ISSUE TITLE
React Native dependency

### ISSUE THREAD

**Issue by kevinresol** [MVCoconut/coconut.react-core#8]
When using with react-native, this compiled code fails:
`tink_domspec_CSSParser.style = window.document.createElement("div").style;`
Because there is no browser/window in RN.

While it can be eliminated with full dce, I think it would be better to work without dce too.

I found that the tink_domspec is added as dependency through `xDom`. So, is `xDom` a must for this library, could it be opt-in?

Or we should add some logic to remove the dependency if the `react-native` define is present.

**Comment by back2dos** [comment]
Hmm, how about we make a coconut.react-dom and coconut.rn?

**Comment by kevinresol** [comment]
coconut.react-native instead of rn, please.

**Comment by back2dos** [comment]
Sounds good ;)
